### ISSUE TITLE
Torch is not able to use an Intel GPU 

### ISSUE THREAD

**Issue by frtzngbllr** [gs1lv4/sd-intel-webui-docker#2]
Hey there, I tried to run your container, but all I run into is this: 
(Am running on win 11 with docker desktrop)

```
2023-07-13 08:45:52 Traceback (most recent call last):
2023-07-13 08:45:52   File "/stable-diffusion-webui/launch.py", line 358, in <module>
2023-07-13 08:45:52     prepare_environment()
2023-07-13 08:45:52   File "/stable-diffusion-webui/launch.py", line 263, in prepare_environment
2023-07-13 08:45:52     run_python("import torch; import intel_extension_for_pytorch; assert torch.xpu.is_available(), 'Torch is not able to use an Intel GPU. Try running without --use-intel-oneapi'")
2023-07-13 08:45:52   File "/stable-diffusion-webui/launch.py", line 120, in run_python
2023-07-13 08:45:52     return run(f'"{python}" -c "{code}"', desc, errdesc)
2023-07-13 08:45:52   File "/stable-diffusion-webui/launch.py", line 96, in run
2023-07-13 08:45:52     raise RuntimeError(message)
2023-07-13 08:45:52 RuntimeError: Error running command.
2023-07-13 08:45:52 Command: "/usr/local/bin/python3" -c "import torch; import intel_extension_for_pytorch; assert torch.xpu.is_available(), 'Torch is not able to use an Intel GPU. Try running without --use-intel-oneapi'"
2023-07-13 08:45:52 Error code: 1
2023-07-13 08:45:52 stdout: <empty>
2023-07-13 08:45:52 stderr: /usr/local/lib/python3.9/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
2023-07-13 08:45:52   warn(f"Failed to load image Python extension: {e}")
2023-07-13 08:45:52 Traceback (most recent call last):
2023-07-13 08:45:52   File "<string>", line 1, in <module>
2023-07-13 08:45:52 AssertionError: Torch is not able to use an Intel GPU. Try running without --use-intel-oneapi
```

**Comment by gdosdev** [comment]
Windows 11 :scream:

I've only tested this out on Linux, and I dont have a windows 11 machine with intel arc to test with. I'm willing to bet its not passing the gpu to to container properly....

https://www.youtube.com/watch?v=wcNxR36aZ6s seems like its got a different device name under windows according to this video

Could you replace these lines in the docker-compose.yml file
```
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
```

with this:
```
    devices:
      - /dev/dxg:/dev/dxg
```

That should hopefully get you past that error. Let me know if this works!
